import _SocketIO from "socket.io";
import _bodyParser from "body-parser";
import _cluster from 'cluster';
import _cookieParser from "cookie-parser";
import _cors from "cors";
import _express from "express";
import _fluidFunc from "fluid-func";
import _fs from "fs";
import _http from "http";
import _httpProxy from "http-proxy";
import _https from "https";
import _log4js from "log4js";
import _mongoose from "mongoose";
import _morgan from "morgan";
import _multipart from "connect-multiparty";
import _net from "net";
import _os from 'os';

export const httpProxy = _httpProxy;
export const cors = _cors;
export const multipart = _multipart;
export const https = _https;
export const http = _http;
export const fs = _fs;
export const morgan = _morgan;
export const express = _express;
export const cookieParser = _cookieParser;
export const bodyParser = _bodyParser;
export const SocketIO = _SocketIO;
export const FluidFunc = _fluidFunc;
export const net = _net;
export const mongoose = _mongoose;
export const cluster = _cluster;
export const os = _os;
export const log4js = _log4js;